[package]
name = "repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
gst = { package = "gstreamer", version = "0.18.7" }
gst-rtsp = { package = "gstreamer-rtsp", version = "0.18.0" }
